In [ ]:
import requests
import pandas as pd

In [ ]:
requests.get("https://api.themoviedb.org/3/movie/popular?api_key=0ba39beea932675c0adabfa57297a080").json()

In [ ]:
response=requests.get("https://api.themoviedb.org/3/movie/popular?api_key=0ba39beea932675c0adabfa57297a080").json()

In [ ]:
popularity=[]
vote_count=[]
original_language=[]
title=[]
vote_average=[]
overview=[]
release_date=[]



for i in response["results"]:
   
    popularity.append(i['popularity'])
    vote_count.append(i['vote_count'])
    original_language.append(i['original_language'])
    title.append(i['title'])
    vote_average.append(i['vote_average'])
    overview.append(i['overview'])
    release_date.append(i['release_date'])
    
d={"title":title,"overview":overview,"vote_count":vote_count,"original_language":original_language,"vote_average":vote_average,"release_date":release_date}

df=pd.DataFrame(d)

df

In [ ]:
final=pd.DataFrame()
for j in range(1501):
    
    response=requests.get("https://api.themoviedb.org/3/movie/popular?api_key=0ba39beea932675c0adabfa57297a080".format(j)).json()
    
    popularity=[]
    vote_count=[]
    original_language=[]
    title=[]
    vote_average=[]
    overview=[]
    release_date=[]



    for i in response["results"]:

        popularity.append(i['popularity'])
        vote_count.append(i['vote_count'])
        original_language.append(i['original_language'])
        title.append(i['title'])
        vote_average.append(i['vote_average'])
        overview.append(i['overview'])
        release_date.append(i['release_date'])

    d={"title":title,"overview":overview,"vote_count":vote_count,"original_language":original_language,"vote_average":vote_average,"release_date":release_date}

    df=pd.DataFrame(d)

    final=final.append(df, ignore_index=True)

In [8]:
final

,title,overview,vote_count,original_language,vote_average,release_date
0,Transformers: Rise of the Beasts,When a new threat capable of destroying the en...,1431,en,7.3,2023-06-06
1,Guardians of the Galaxy Vol. 3,"Peter Quill, still reeling from the loss of Ga...",3234,en,8.1,2023-05-03
2,Warhorse One,A gunned down Navy SEAL Master Chief must guid...,15,en,5.9,2023-06-30
3,The Flash,When his attempt to save his family inadverten...,1128,en,6.9,2023-06-13
4,Barbie,Barbie and Ken are having the time of their li...,107,en,8.2,2023-07-19
...,...,...,...,...,...,...
14675,San Andreas,In the aftermath of a massive earthquake in Ca...,7829,en,6.2,2015-05-27
14676,Sheroes,When four thick-as-thieves friends arrive in T...,62,en,6.0,2023-06-23
14677,The Darkest Minds,After a disease kills 98% of America's childre...,2501,en,7.0,2018-07-25
14678,The Little Mermaid,"The youngest of King Triton’s daughters, and t...",890,en,6.3,2023-05-18
14679,Mission: Impossible - Dead Reckoning Part One,Ethan Hunt and his IMF team embark on their mo...,486,en,7.9,2023-07-08